CREATE TABLE IF NOT EXISTS USER (
  id INT AUTO_INCREMENT NOT NULL,
  email VARCHAR(255) NOT NULL,
  balance FLOAT NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS POSITION (
  id INT AUTO_INCREMENT NOT NULL,
  id_user INT NOT NULL ,
  id_coin INT NOT NULL ,
  price FLOAT NOT NULL ,
  amounts FLOAT NOT NULL,
  date DATETIME NOT NULL ,
  type VARCHAR(5) NOT NULL,
  FOREIGN KEY (id_user) REFERENCES USERS (id),
  FOREIGN KEY (id_coin) REFERENCES COINS (id),
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS COIN (
  id INT AUTO_INCREMENT,
  uuid INT NOT NULL,
  symbol VARCHAR(5) NOT NULL,
  name VARCHAR(64) NOT NULL ,
  iconUrl VARCHAR(256) NOT NULL,
  marketCap INT NOT NULL,
  price FLOAT NOT NULL,
  priceChange FLOAT NOT NULL,
  volumen24 VARCHAR(64) NOT NULL,
  PRIMARY KEY (id)
);